name: Metrics
on:
  # Se actualiza cada 24 horas
  schedule: [{cron: "0 0 * * *"}]
  # Permite ejecuci√≥n manual
  workflow_dispatch:
  # Se ejecuta cada vez que haces un push a la rama main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Bimbitor
          template: classic
          base: header, community, repositories, metadata
          config_timezone: America/Bogota
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all
